# Generated by Django 3.0.5 on 2020-04-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200401_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('kan', 'Kannada'), ('oth', 'Others')], default='Kannada', max_length=7),
        ),
    ]
