# Generated by Django 3.0.5 on 2020-04-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200404_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(related_name='blog_categories', to='blog.Category'),
        ),
    ]
