# Generated by Django 3.0.5 on 2020-04-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200404_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-posted',)},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Kannada', 'Kannada'), ('Others', 'Others')], default='Kannada', max_length=7),
        ),
    ]
